#!/usr/bin/env python3
import bcrypt

def bcrypt10():

	# Import is intentionally delayed.
	import sys

	# Compute based on stdin
	password = sys.stdin.read()
	binary = password.encode("UTF-8")
	hashed = bcrypt.hashpw(binary, bcrypt.gensalt())
	print(hashed.decode("UTF-8"))

if __name__ == "__main__":
	try:
		bcrypt10()
	except KeyboardInterrupt:
		pass
