#!/bin/bash

set -euo pipefail

say()
{
	echo -e "$(date -Isec): ${@}"
}

[ -v BASE_DIR ] || BASE_DIR="/app"
[ -v INIT_DIR ] || INIT_DIR="${BASE_DIR}/init"

###################################################################
# UPDATE CA CERTIFICATES                                          #
###################################################################
[ -v SSL_DIR ] || SSL_DIR="/.ssl"
export ACME_SUPPORT_JCEKS="true"
/usr/local/bin/acme-init

#
# Add the requisite CATALINA_OPTS carrying certificate passwords (not the cleanest way, but
# Alfresco isn't smart enough to do better)
#
[ -v CATALINA_OPTS ] || CATALINA_OPTS=""
CATALINA_OPTS+=" -Dencryption.ssl.truststore.location=/etc/pki/java/cacerts -Dencryption.ssl.truststore.type=JKS"
if [ -f "${SSL_DIR}/keystore.pass" ] && [ -f "${SSL_DIR}/keystore.pkcs12" ] ; then
	KEYSTORE_PASSWORD="$(<"${SSL_DIR}/keystore.pass")"
	CATALINA_OPTS+=" -Dencryption.ssl.keystore.location=${SSL_DIR}/keystore.pkcs12 -Dencryption.ssl.keystore.type=PKCS12"
	CATALINA_OPTS+=" -Dssl-keystore.password=${KEYSTORE_PASSWORD} -Dssl-keystore.aliases=acme -Dssl-keystore.acme.password=${KEYSTORE_PASSWORD}"
fi
export CATALINA_OPTS

#
# Finally, if our admin password is set in a envvar, and the MD4 tool
# is available in the path, create an MD4 version of the admin password
# and make it available downstream
#
if type -P md4 &>/dev/null ; then
	[ -v ALFRESCO_ADMIN_PASSWORD_VAR ] || ALFRESCO_ADMIN_PASSWORD_VAR=""
	[ -n "${ALFRESCO_ADMIN_PASSWORD_VAR}" ] || ALFRESCO_ADMIN_PASSWORD_VAR="ALFRESCO_ADMIN_PASSWORD"
	if [[ "${ALFRESCO_ADMIN_PASSWORD_VAR}" =~ ^[_a-zA-Z][_a-zA-Z0-9]*$ ]] ; then
		if [ -v "${ALFRESCO_ADMIN_PASSWORD_VAR}" ] ; then
			V="$(echo -n "${!ALFRESCO_ADMIN_PASSWORD_VAR}" | md4)"
			eval export "${ALFRESCO_ADMIN_PASSWORD_VAR}_MD4=${V@Q}"
		else
			say "⚠️ The administrator password variable [${ALFRESCO_ADMIN_PASSWORD_VAR}] is not set"
		fi
	else
		say "⚠️ The ALFRESCO_ADMIN_PASSWORD_VAR value [${ALFRESCO_ADMIN_PASSWORD_VAR}] is not a valid environment variable name"
	fi
else
	say "⚠️ The md4 tool was not found, will not try to set the administrator password"
fi

# Finally, do environment substitution on the alfresco-global.properties file
while read SRC ; do

	[ -r "${SRC}" ] || continue

	# Remove the ".tpl" suffix
	TGT="${SRC%.*}"
	[ -n "${TGT}" ] || continue

	# Can we write to the target file? We can write to the target
    # file if it doesn't exist, or exists and is writable.
	[ -f "${TGT}" ] && [ ! -w "${TGT}" ] && say "⚠️ Can't expand the environment variables for [${TGT}] - the file exists but is not writable" && continue

	# Do the deed!
	say "📝 Expanding environment variables for [${TGT}]"
	envsubst < "${SRC}" > "${TGT}"

done < <(find /usr/local/tomcat/shared/classes -type f -iname '*.tpl' | sort)

exec "${CATALINA_HOME}/bin/catalina.sh" run -security
