#!/bin/bash

set -euo pipefail
. /.functions

#
# Init all the SSL-related stuff
#
init_ssl

#
# Add the requisite CATALINA_OPTS carrying certificate passwords (not the cleanest way, but
# Alfresco isn't smart enough to do better)
#
set_or_default CATALINA_OPTS
SSL_OPTS=(
	-Dencryption.ssl.keystore.location="${JAVA_KEYSTORE}"
	-Dencryption.ssl.keystore.type="${JAVA_KEYSTORE_TYPE}"

	-Dssl-keystore.password="${JAVA_KEYSTORE_PASSWORD}"
	-Dssl-keystore.aliases="${JAVA_KEY_ALIAS}"
	"-Dssl-keystore.${JAVA_KEY_ALIAS}.password=${JAVA_KEY_PASSWORD}"

	-Dencryption.ssl.truststore.location="${JAVA_TRUSTSTORE}"
	-Dencryption.ssl.truststore.type="${JAVA_TRUSTSTORE_TYPE}"
)
CATALINA_OPTS+=" ${SSL_OPTS[@]}"
export CATALINA_OPTS
unset SSL_OPTS

#
# Finally, if our admin password is set in an envvar, and the MD4 tool
# is available in the path, create an MD4 version of the admin password
# and make it available downstream
#
if type -P md4 &>/dev/null ; then
	[ -v ALFRESCO_ADMIN_PASSWORD_VAR ] || ALFRESCO_ADMIN_PASSWORD_VAR=""
	[ -n "${ALFRESCO_ADMIN_PASSWORD_VAR}" ] || ALFRESCO_ADMIN_PASSWORD_VAR="ALFRESCO_ADMIN_PASSWORD"
	if [[ "${ALFRESCO_ADMIN_PASSWORD_VAR}" =~ ^[_a-zA-Z][_a-zA-Z0-9]*$ ]] ; then
		if [ -v "${ALFRESCO_ADMIN_PASSWORD_VAR}" ] ; then
			V="$(echo -n "${!ALFRESCO_ADMIN_PASSWORD_VAR}" | md4)"
			eval export "${ALFRESCO_ADMIN_PASSWORD_VAR}_MD4=${V@Q}"
		else
			warn "The administrator password variable [${ALFRESCO_ADMIN_PASSWORD_VAR}] is not set"
		fi
	else
		warn "The ALFRESCO_ADMIN_PASSWORD_VAR value [${ALFRESCO_ADMIN_PASSWORD_VAR}] is not a valid environment variable name"
	fi
else
	warn "The md4 tool was not found, will not try to set the administrator password"
fi

# Finally, do environment substitution on any template files
while read SRC ; do

	[ -r "${SRC}" ] || continue

	# Remove the ".tpl" suffix
	TGT="${SRC%.*}"
	[ -n "${TGT}" ] || continue

	# Can we write to the target file? We can write to the target
	# file if it doesn't exist, or exists and is writable.
	[ -f "${TGT}" ] && [ ! -w "${TGT}" ] && warn "Can't expand the environment variables for [${TGT}] - the file exists but is not writable" && continue

	# Do the deed!
	say "📝 Expanding environment variables for [${TGT}]"
	envsubst < "${SRC}" > "${TGT}"

done < <(find /usr/local/tomcat/shared/classes -type f -iname '*.tpl' | sort)

set_as_boolean ALFRESCO_PASSWORD_RESET "false"
if as_boolean "${ALFRESCO_PASSWORD_RESET}" ; then
	say "📝 Resetting the Alfresco password for the user ${ALFRESCO_ADMIN_USERNAME} (and admin, just in case)"
	java -jar "${CATALINA_HOME}/alfresco-password-reset.jar" "\${${ALFRESCO_ADMIN_PASSWORD_VAR}}" "admin" "${ALFRESCO_ADMIN_USERNAME}"
fi

execute "${CATALINA_HOME}/bin/catalina.sh" run -security
